---
- hosts: all
  name: Pl
  become: true
  tasks:
    - name: Stopped
      docker_container:
        name: '{{ lookup("env","SERVICE_NAME") }}'
        state: stopped
        recreate: no
    - name: Remove Stopped
      ansible.builtin.shell:
          docker rm '{{ lookup("env","SERVICE_NAME") }}'
    - name: Pull image and start docker container 
      community.docker.docker_container:
        name: '{{ lookup("env","SERVICE_NAME") }}'
        image: '{{ lookup("env","image") }}'
        ports:
          - "8080:8080"
        restart_policy: always
