- name: Install dependencies
  apt:
    name: golang

- name: Copy application files
  copy:
    src: /home/jetigenov/myapp
    dest: /opt/myapp

- name: Build application
  command: go build -o /opt/myapp/myapp /opt/myapp/main.go

- name: Create systemd service
  copy:
    src: system/serverapp.service
    dest: /etc/systemd/system/serverapp.service

- name: Reload systemd
  systemd:
    daemon_reload: yes

- name: Enable and start systemd service
  systemd:
    name: myapp
    enabled: yes
    state: started
