---
- name: Deploy Docker container
  hosts: all
  become: true
  gather_facts: false

  tasks:
    - name: Stop running containers
      docker_container:
        name: "{{ lookup('env', 'SERVICE_NAME') }}"
        state: stopped
        recreate: no

    - name: Remove stopped containers
      ansible.builtin.shell:
        docker rm '{{ lookup("env","SERVICE_NAME") }}'
      register: containers_to_remove

    - name: Pull image
      docker_image:
        name: "{{ lookup('env', 'IMAGE') }}"
        source: pull

    - name: Start container
      docker_container:
        name: "{{ lookup('env', 'SERVICE_NAME') }}"
        image: "{{ lookup('env', 'IMAGE') }}"
        state: started
        ports:
          - "8080:8080"
        restart_policy: always
