name: Build and Deploy Docker Image

on:
  push:
    branches:
      - main

env:
  PROD_IP_CENTOS: 192.168.1.112

jobs:
  build:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout code
        uses: actions/checkout@v2
      
      - name: Login to Docker Hub
        uses: docker/login-action@v2
        with:
          username: ${{ secrets.DOCKERHUB_USERNAME }}
          password: ${{ secrets.DOCKERHUB_PASSWORD }}
      - name: Set up Docker Buildx
        uses: docker/setup-buildx-action@v2
      
      - name: Build and push Docker image
        run: |
          docker build -t $DOCKER_USERNAME/$GITHUB_REPOSITORY:${GITHUB_SHA::8} .
          docker push $DOCKER_USERNAME/$GITHUB_REPOSITORY:${GITHUB_SHA::8}
  deploy:
    runs-on: ubuntu-latest
    steps:
      - name: Deploy Docker image to production
        uses: appleboy/ssh-action@master
        with:
          host: ${{ env.PROD_IP_CENTOS }}
          username: ${{ secrets.PROD_USERNAME }}
          key: ${{ env.SSH_PRIVATE_KEY }}
          script: |
            ansible-playbook /path/to/playbook.yml --extra-vars "image=$DOCKER_USERNAME/$GITHUB_REPOSITORY:${GITHUB_SHA::8}"
