name: Build and Deploy

on:
  push:
    branches:
      - "main"

env:
  SERVICE_NAME: chyngyz91
  DOCKER_REGISTRY_URL: docker.io
  DOCKER_USERNAME: ${{ secrets.DOCKER_USERNAME }}
  DOCKER_PASSWORD: ${{ secrets.DOCKER_PASSWORD }}
jobs:
  build-and-push:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout code
        uses: actions/checkout@v2

      - name: Login to Docker Hub
        uses: docker/login-action@v1
        with:
          registry: ${{ env.DOCKER_REGISTRY_URL }}
          username: ${{ env.DOCKER_USERNAME }}
          password: ${{ env.DOCKER_PASSWORD }}

      - name: Build Docker image
        run: docker build -t ${{ env.SERVICE_NAME }} .

      - name: Push Docker image
        uses: docker/build-push-action@v2
        with:
          context: .
          file: ./Dockerfile
          push: true
          tags: chyngyz91/myappgo


  deploy:
     runs-on: ubuntu-latest
     steps:
      - uses: actions/checkout@v1
      - uses: ./.github/actions/deploy/action.yml
        env:
            VAULT_PASS: ${{ secrets.VAULT_PASS }}
