name: Deploy to Production

on:
  push:
    branches:
      - main

jobs:
  deploy:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout code
        uses: actions/checkout@v2

      - name: Install dependencies
        run: |
          sudo apt update
          sudo apt install -y ansible docker.io

      - name: Build Docker image
        run: docker build -t myapp .

      - name: Deploy with Ansible
        run: |
          ansible-playbook ./playbook.yml

      - name: Run in Docker container
        run: docker run -d --name myapp -p 8080:8080 myapp
