name: Deploy to Production

on:
  push:
    branches:
      - main

env:
  IMAGE_NAME: myimage
  CONTAINER_NAME: mycontainer
  PROD_SERVER: prod.example.com

jobs:
  deploy:
    runs-on: ubuntu-latest

    steps:
    - name: Checkout code
      uses: actions/checkout@v2

    - name: Login to Docker Hub
      run: echo "${{ secrets.DOCKERHUB_PASSWORD }}" | docker login --username "${{ secrets.DOCKERHUB_USERNAME }}" --password-stdin

    - name: Build Docker image
      run: docker build -t ${{ env.IMAGE_NAME }} .

    - name: Push Docker image
      run: docker push ${{ env.IMAGE_NAME }}

    - name: Deploy to production server
      uses: appleboy/ssh-action@master
      with:
        host: ${{ env.PROD_SERVER }}
        username: ${{ secrets.SERVER_USERNAME }}
        key: ${{ secrets.SERVER_SSH_KEY }}
        script: |
          docker stop ${{ env.CONTAINER_NAME }} || true
          docker rm ${{ env.CONTAINER_NAME }} || true
          docker run -d --name ${{ env.CONTAINER_NAME }} -p 80:80 ${{ env.IMAGE_NAME }}
