name: Build, Push, and Deploy Docker Image

on:
  push:
    branches:
      - main

env:
    docker_registry_username: ${{ secrets.DOCKER_USERNAME }}
    docker_registry_password: ${{ secrets.DOCKER_PASSWORD }}

jobs:
  build:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout code
        uses: actions/checkout@v2

      - name: Install dependencies
        run: |
          sudo apt-get update && \
          sudo apt-get install -y python3-pip && \
          pip3 install ansible && \
          ansible-galaxy collection install community.docker
  deploy:
     runs-on: ubuntu-latest
     steps:
      - name: Build, push, and deploy Docker image
        run: |
          ansible-playbook ansible/playbook.yml \
          --extra-vars "docker_registry_username=$DOCKER_USERNAME docker_registry_password=$DOCKER_PASSWORD"
