name: Build and Deploy

on:
  push:
    branches:
      - "main"

env:
  SERVICE_NAME: chyngyz91
  DOCKER_REGISTRY_URL: docker.io
  DOCKER_USERNAME: ${{ secrets.DOCKER_USERNAME }}
  DOCKER_PASSWORD: ${{ secrets.DOCKER_PASSWORD }}

jobs:
  build-and-push:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout code
        uses: actions/checkout@v2

      - name: Login to Docker Hub
        uses: docker/login-action@v1
        with:
          registry: ${{ env.DOCKER_REGISTRY_URL }}
          username: ${{ env.DOCKER_USERNAME }}
          password: ${{ env.DOCKER_PASSWORD }}

      - name: Build Docker image
        run: docker build -t ${{ env.SERVICE_NAME }} .
        
      - name: Push Docker image
        uses: docker/build-push-action@v2
        with:
          context: .
          file: ./Dockerfile
          push: true
          tags: chyngyz91/myappgo
  deploy:
    needs: build-and-push
    runs-on: ubuntu-latest

    steps:
          
       - name: Install SSH key
         uses: shimataro/ssh-key-action@v2
         with:
                 key: ${{ secrets.SSH_KEY }}
                 name: id_rsa
                 known_hosts: ${{ secrets.KNOWN_HOSTS }}
                 if_key_exists: fail
                 
       - name: run playbook
         run: |
            ansible-playbook -i ./hosts ./playbook.yml
