name: Build and Deploy

on:
  push:
    branches:
      - "main"

env:
  SERVICE_NAME: chyngyz91
  IMAGE_TAG: ${{ github.sha }}
  DOCKER_REGISTRY_URL: docker.io
  DOCKER_USERNAME: ${{ secrets.DOCKER_USERNAME }}
  DOCKER_PASSWORD: ${{ secrets.DOCKER_PASSWORD }}
  SSH_PRIVATE_KEY: ${{ secrets.SSH_PRIVATE_KEY }}
  SSH_KNOWN_HOSTS: ${{ secrets.SSH_KNOWN_HOSTS }}
  REMOTE_USER: jetigenov
  REMOTE_HOST: 192.168.1.112
  ANSIBLE_INVENTORY: ././hosts.yaml
  ANSIBLE_PLAYBOOK: ././playbook.yaml

jobs:
  build-and-push:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout code
        uses: actions/checkout@v2

      - name: Login to Docker Hub
        uses: docker/login-action@v1
        with:
          registry: ${{ env.DOCKER_REGISTRY_URL }}
          username: ${{ env.DOCKER_USERNAME }}
          password: ${{ env.DOCKER_PASSWORD }}

      - name: Build Docker image
        run: docker build -t ${{ env.SERVICE_NAME }} .
        
      - name: Push Docker image
        uses: docker/build-push-action@v2
        with:
          context: .
          file: ./Dockerfile
          push: true
          tags: chyngyz91/myappgo
  deploy:
    needs: build-and-push
    runs-on: ubuntu-latest

    steps:
          
      - name: Deploy with Ansible
        run: |
          ansible-playbook --user $USER -i ././hosts.yaml --become --become-user=root ././playbook.yaml
