name: Build and Deploy

on:
  push:
    branches:
      - "main"

env:
  SERVICE_NAME: chyngyz91
  DOCKER_REGISTRY_URL: docker.io
  DOCKER_USERNAME: ${{ secrets.DOCKER_USERNAME }}
  DOCKER_PASSWORD: ${{ secrets.DOCKER_PASSWORD }}

jobs:
  build-and-push:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout code
        uses: actions/checkout@v2

      - name: Login to Docker Hub
        uses: docker/login-action@v1
        with:
          registry: ${{ env.DOCKER_REGISTRY_URL }}
          username: ${{ env.DOCKER_USERNAME }}
          password: ${{ env.DOCKER_PASSWORD }}

      - name: Build Docker image
        run: docker build -t ${{ env.SERVICE_NAME }} .
        
      - name: Push Docker image
        uses: docker/build-push-action@v2
        with:
          context: .
          file: ./Dockerfile
          push: true
          tags: chyngyz91/myappgo
  deploy:
    needs: build-and-push
    runs-on: ubuntu-latest

    steps:
    
       - uses: actions/checkout@v3
         with:
          submodules: true
          token: ${{secrets.REPO_TOKEN}}
       - name: Setup SSH 
         shell: bash
         run: |
          eval `ssh-agent -s`
          mkdir -p /home/jetigenov/.ssh/
          touch /home/jetigenov/.ssh/id_rsa
          echo -e "${{secrets.SSH_KEY}}" > /home/runner/.ssh/id_rsa
          chmod 700 /home/jetigenov/.ssh/id_rsa
          ssh-keyscan -t rsa,dsa,ecdsa,ed25519 ${{secrets.SSH_HOST}} >> /home/jetigenov/.ssh/known_hosts
       - name: Run ansible script
         shell: bash 
         run: |
          service ssh status
          cd infrastructure/ansible
          cat setup-prod.yml
          ansible-playbook -vvv --private-key /home/jetigenov/.ssh/id_rsa -u ${{secrets.ANSIBLE_DEPLOY_USER}} -i hosts playbook.yml
