name: Build and Deploy Docker Image

on:
  push:
    branches:
      - main

env:
  DOCKER_USERNAME: ${{ secrets.DOCKER_USERNAME }}
  DOCKER_PASSWORD: ${{ secrets.DOCKER_PASSWORD }}
  SSH_PRIVATE_KEY: ${{ secrets.SSH_PRIVATE_KEY }}
  PROD_IP_CENTOS: 192.168.1.112

jobs:
  build:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout code
        uses: actions/checkout@v2

      - name: Login to Docker registry
        run: echo "$DOCKER_PASSWORD" | docker login -u "$DOCKER_USERNAME" --password-stdin

      - name: Build and push Docker image
        run: |
          docker build -t $DOCKER_USERNAME/$GITHUB_REPOSITORY:${GITHUB_SHA::8} .
          docker push $DOCKER_USERNAME/$GITHUB_REPOSITORY:${GITHUB_SHA::8}

      - name: Deploy Docker image to production
        uses: appleboy/ssh-action@master
        with:
          host: ${{ env.PROD_IP_CENTOS }}
          username: ${{ secrets.PROD_USERNAME }}
          key: ${{ env.SSH_PRIVATE_KEY }}
          script: |
            ansible-playbook /path/to/playbook.yml --extra-vars "image=$DOCKER_USERNAME/$GITHUB_REPOSITORY:${GITHUB_SHA::8}"
